# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.CharField(blank=True, max_length=20, null=True)),
                ('Password', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'ordering': ['pk'],
                'db_table': 'doctor_details',
                'managed': True,
                'verbose_name_plural': 'doctor_details',
            },
        ),
        migrations.CreateModel(
            name='patient_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.CharField(blank=True, max_length=20, null=True)),
                ('Password', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'ordering': ['pk'],
                'db_table': 'patient_details',
                'managed': True,
                'verbose_name_plural': 'patient_details',
            },
        ),
    ]
