# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc_prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Age', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.CharField(blank=True, max_length=20, null=True)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Diagnosis', models.CharField(blank=True, max_length=100, null=True)),
                ('Remedies', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['pk'],
                'db_table': 'doc_prescription',
                'managed': True,
                'verbose_name_plural': 'doc_prescriptions',
            },
        ),
    ]
