# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_doc_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_prescription',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
